"""cria tabela cempre_emprego

Revision ID: c54a3a3e7feb
Revises: ff49cd00f76d
Create Date: 2026-10-05 14:22:57.132731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54a3a3e7feb'
down_revision: Union[str, Sequence[str], None] = 'ff49cd00f76d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cempre_emprego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.String(length=4), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('unidades_locais', sa.Integer(), nullable=False),
    sa.Column('pessoal_ocupado', sa.Integer(), nullable=False),
    sa.Column('salario_medio', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'setor', name='uq_ano_setor_cempre')
    )
    op.create_index(op.f('ix_cempre_emprego_ano'), 'cempre_emprego', ['ano'], unique=False)
    op.create_index(op.f('ix_cempre_emprego_id'), 'cempre_emprego', ['id'], unique=False)
    op.create_index(op.f('ix_cempre_emprego_setor'), 'cempre_emprego', ['setor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cempre_emprego_setor'), table_name='cempre_emprego')
    op.drop_index(op.f('ix_cempre_emprego_id'), table_name='cempre_emprego')
    op.drop_index(op.f('ix_cempre_emprego_ano'), table_name='cempre_emprego')
    op.drop_table('cempre_emprego')
    # ### end Alembic commands ###
